# Changes here will be overwritten by Copier
_commit: 1.5.6
_src_path: gh:pawamoy/copier-uv
author_email: jean-michel.perraud@csiro.au
author_fullname: J-M
author_username: jmp75
copyright_date: '2025'
copyright_holder: CSIRO
copyright_holder_email: jean-michel.perraud@csiro.au
copyright_license: MIT License
insiders: false
project_description: Python classes for reference counting
project_name: refcount
python_package_command_line_name: ''
python_package_distribution_name: refcount
python_package_import_name: refcount
repository_name: pyrefcount
repository_namespace: csiro-hydroinformatics
repository_provider: github.com

