site_name: refcount

theme:
  name: "readthedocs"
  # name: "material"

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Usage and Application: usage-and-applications.md
  - Code Documentation: code-reference.md
  - Appendix:
      - Tech Notes: tech_notes.md
